In [ ]:
import numpy as np

# Tạo ma trận A và B
A = np.array([[1, 1], [8, 2]])
B = np.array([[1, 8], [4, 8]])

# Cộng hai ma trận
C = A + B

# Trừ hai ma trận
D = A - B

print("Ma trận A:\n", A)
print("Ma trận B:\n", B)
print("Tổng 2 ma trận:\n", C)
print("Hiệu 2 ma trận:\n", D)

Ma trận A:
 [[1 1]
 [8 2]]
Ma trận B:
 [[1 8]
 [4 8]]
Tổng 2 ma trận:
 [[ 2  9]
 [12 10]]
Hiệu 2 ma trận:
 [[ 0 -7]
 [ 4 -6]]


In [ ]:
import pandas as pd

# Dữ liệu từ bảng được cung cấp sẵn
data = {
    'X': [78, 85, 80, 96, 86],
    'Y': [84, 94, 83, 94, 86],
    'Z': [86, 97, 73, 96, 83]
}

# Tạo DataFrame từ dữ liệu
df = pd.DataFrame(data, index=[1, 2, 3, 4, 5])

# Lưu DataFrame vào tập tin CSV
df.to_csv('Lab1_Bai2.csv', index=True)

In [ ]:
import pandas as pd
import numpy as np

# Đọc tập tin CSV vào DataFrame
df = pd.read_csv('Lab1_Bai2.csv', index_col=0)
print("Đọc CSV thành Dataframe và hiển thị:")
print(df)

Đọc CSV thành Dataframe và hiển thị:
    X   Y   Z
1  78  84  86
2  85  94  97
3  80  83  73
4  96  94  96
5  86  86  83


In [ ]:
import pandas as pd

# Chuyển index mặc định thành giá trị cột id
df = pd.read_csv('Lab1_Bai2.csv')
df.rename(columns={'Unnamed: 0': 'id'}, inplace=True)
df.set_index('id', inplace=True)
print(df)
df.to_csv('Lab1_Bai2.csv', index=True, index_label='id')

     X   Y   Z
id            
1   78  84  86
2   85  94  97
3   80  83  73
4   96  94  96
5   86  86  83


In [ ]:
import pandas as pd

# Sắp xếp dữ liệu theo cột X và Y
df = pd.read_csv('Lab1_Bai2.csv')
df.set_index('id', inplace=True)
df_sorted = df.sort_values(by=['X', 'Y'])
print("\nDataFrame sau khi sắp xếp theo X và Y:")
print(df_sorted)
df_sorted.to_csv('Lab1_Bai2.csv', index=True, index_label='id')


DataFrame sau khi sắp xếp theo X và Y:
     X   Y   Z
id            
1   78  84  86
3   80  83  73
2   85  94  97
5   86  86  83
4   96  94  96


In [ ]:
import pandas as pd

#Chọn một cột cụ thể và hiển thị nó (chọn cột Z)
df = pd.read_csv('Lab1_Bai2.csv')
df.set_index('id', inplace=True)
column_z = df['Z']
print("\nCột Z:")
print(column_z)


Cột Z:
id
1    86
3    73
2    97
5    83
4    96
Name: Z, dtype: int64


In [ ]:
import pandas as pd

# Chọn 2 hàng đầu tiên và hiển thị chúng
df = pd.read_csv('Lab1_Bai2.csv')
df.set_index('id', inplace=True)
first_two_rows = df.head(2)
print("\nHai hàng đầu tiên của DataFrame:")
print(first_two_rows)


Hai hàng đầu tiên của DataFrame:
     X   Y   Z
id            
1   78  84  86
3   80  83  73


In [ ]:
import pandas as pd

# Chọn một hàng dựa trên một điều kiện cụ thể của cột (Z = 97)
df = pd.read_csv('Lab1_Bai2.csv')
df.set_index('id', inplace=True)
row_condition = df[df['Z'] == 97]
print("\nHàng với điều kiện Z = 97:")
print(row_condition)


Hàng với điều kiện Z = 97:
     X   Y   Z
id            
2   85  94  97


In [ ]:
import pandas as pd

# Thay đổi một vài giá trị thành NaN và sau đó thay thế chúng bằng giá trị 0
df = pd.read_csv('Lab1_Bai2.csv')
df.set_index('id', inplace=True)
df.loc[3, 'X'] = np.nan
df.loc[2, 'Y'] = np.nan
df = df.fillna(0).astype('Int64')
print("\nDataFrame sau khi thay thế NaN bằng 0:")
print(df)
df.to_csv('Lab1_Bai2.csv', index=True, index_label='id')


DataFrame sau khi thay thế NaN bằng 0:
     X   Y   Z
id            
1   78  84  86
3    0  83  73
2   85   0  97
5   86  86  83
4   96  94  96


In [ ]:
import pandas as pd

# Trong cột Z chuyển giá trị lớn hơn 90 là True và nhỏ hơn hoặc bằng là False
df = pd.read_csv('Lab1_Bai2.csv')
df.set_index('id', inplace=True)
df['Z'] = df['Z'] > 90
print("\nDataFrame cột Z sau khi chuyển giá trị lớn hơn 90 là True và bé hơn là False:")
print(df)


DataFrame cột Z sau khi chuyển giá trị lớn hơn 90 là True và bé hơn là False:
     X   Y      Z
id               
1   78  84  False
3    0  83  False
2   85   0   True
5   86  86  False
4   96  94   True


In [ ]:
import pandas as pd

# Chuyển DataFrame thành 2 DataFrame d1 và d2; d1 chứa cột X và Y, d2 chứa cột Z
df = pd.read_csv('Lab1_Bai2.csv')
df.set_index('id', inplace=True)
d1 = df[['X', 'Y']]
d2 = df[['Z']]
print("\nDataFrame d1:")
print(d1)
print("\nDataFrame d2:")
print(d2)

# Nối d1 và d2 theo cột
df_concatenated = pd.concat([d1, d2], axis=1)
print("\nDataFrame sau khi ghép d1 và d2:")
print(df_concatenated)


DataFrame d1:
     X   Y
id        
1   78  84
3    0  83
2   85   0
5   86  86
4   96  94

DataFrame d2:
     Z
id    
1   86
3   73
2   97
5   83
4   96

DataFrame sau khi ghép d1 và d2:
     X   Y   Z
id            
1   78  84  86
3    0  83  73
2   85   0  97
5   86  86  83
4   96  94  96


In [ ]:
import pandas as pd

# Dùng tính năng thống kê để hiển thị kết quả thông kê các giá trị thuộc tính của DataFrame
df = pd.read_csv('Lab1_Bai2.csv')
df.set_index('id', inplace=True)
statistics = df.describe()
print("\nThống kê cơ bản của DataFrame:")
print(statistics)


Thống kê cơ bản của DataFrame:
              X          Y          Z
count   5.00000   5.000000   5.000000
mean   69.00000  69.400000  87.000000
std    39.10243  39.035881   9.924717
min     0.00000   0.000000  73.000000
25%    78.00000  83.000000  83.000000
50%    85.00000  84.000000  86.000000
75%    86.00000  86.000000  96.000000
max    96.00000  94.000000  97.000000
